name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: npm install

      - name: Fetch i18n files
        run: |
          curl -o assets/i18n/fa.json https://sadeghsourcecode.github.io/market/assets/i18n/fa.json

      - name: Build the project
        run: npm run build -- --configuration production --base-href=/market/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: gh-pages 
          folder: dist/market/browser